export interface RuleSection {
  title: string;
  body: string;
}

export const RULES_SECTIONS: RuleSection[] = [
  {
    title: 'Setup',
    body: `OPTIONAL: Select an Adversary and/or Scenario. Follow any specified setup instructions.

NEW PLAYERS:
- Choose a low-complexity Spirit (Lightning's Swift Strike, Vital Strength of the Earth, River Surges in Sunlight, or Shadows Flicker Like Flame).
- Take the Power Progression Card for your Spirit. Set aside all Major and Minor Powers listed and, when gaining a new Power Card during the game, add the next Power Card listed instead.
- Do not use a Blight Card, Adversary, or Scenario.

INVADER BOARD:
- Place to one side of play area.
- Place 4 Fear Markers per player into the Fear Pool.
- Shuffle the Fear Cards and place 9 on the Fear Deck Space. Divide the deck into 3 groups of 3 cards each. Place the "Terror Level 2" divider between the top and middle groups. Place the "Terror Level 3" divider between the middle and bottom groups.
- Invader Deck: Shuffle the cards from each Stage separately. Select 5 Stage III cards and place them on the Invader Board on the Explore Action Space. Select 4 Stage II cards and place them on top of the Stage III cards. Then select 3 Stage I cards and place them on top to complete the Invader Deck.
- Take a random Blight Card and cover the Blight Space, "Healthy Island" side up, without looking at the back.
- Place the shown amount of Blight on the card/board.`,
  },
  {
    title: 'Sequence of Play',
    body: `Each turn has the following phases:

1. SPIRIT PHASE
   1. Growth
   2. Gain Energy
   3. Play and Pay for Power Cards

2. FAST POWER PHASE (Cards and Innate)

3. INVADER PHASE
   1. Blighted Island Effect (once appropriate)
   2. Fear Effects
   3. Invader Actions
      a. Ravage
      b. Build
      c. Explore
   4. Advance Invader Cards

4. SLOW POWER PHASE (Cards and Innate)

5. TIME PASSES

Play is simultaneous within each phase.`,
  },
  {
    title: 'Spirit Phase',
    body: `GROWTH:
Choose 1 option (unless stated otherwise) next to "Growth" at the upper-right of the Spirit Panel. You must do everything shown, but may choose the order.

Common Growth Options:
- Add 1 Presence at Range 2.
- Gain 2 Energy.
- Gain a Power Card.
- Reclaim all played Power Cards from your discard pile.

GAIN ENERGY:
Gain Energy equal to the highest uncovered number on your Energy Presence Track.

PLAY AND PAY FOR POWER CARDS:
Select up to your Card Plays. Pay Energy immediately and gain all Elements. Card effects resolve in their phase (Fast or Slow).`,
  },
  {
    title: 'Invader Phase',
    body: `BLIGHTED ISLAND: If the Blight Card has flipped, follow its instructions.

FEAR: Resolve any earned Fear Cards in earned order, using the effect for the current Terror Level.

RAVAGE: Invaders Ravage in lands of the shown type:
  Explorers = 1 Damage | Towns = 2 Damage | Cities = 3 Damage
Reduce by any Defend played in that land.
1. Land takes Blight if ≥2 damage (cascades from already-blighted lands; destroys 1 Presence per Spirit in the land).
2. Invaders damage Dahan (every 2 Damage destroys 1 Dahan).
3. Surviving Dahan fight back: each deals 2 Damage to Invaders.
   - Destroying a Town generates 1 Fear.
   - Destroying a City generates 2 Fear.

BUILD: In each land of the shown type with Invaders:
- If more Towns than Cities: add a City.
- Else: add a Town.

EXPLORE: Reveal top of Invader Deck. In lands of the shown type, add 1 Explorer if the land contains a Town/City OR is adjacent to one OR is coastal. If the deck is empty when you must draw, you lose.

ADVANCE: Slide Invader Cards left (Ravage discards, Build → Ravage, Explore → Build).`,
  },
  {
    title: 'Victory & Defeat',
    body: `VICTORY (by Terror Level):
- TL 1: No Invaders on the island.
- TL 2: No Cities and no Towns.
- TL 3: No Cities.

DEFEAT:
- Too Much Blight: Last Blight comes off the Blight Card and triggers loss.
- A Spirit Is Destroyed: A Spirit has no Presence left on the island.
- Time Runs Out: Empty Invader Deck when Explore needs a draw.`,
  },
  {
    title: 'Fear & Terror',
    body: `Fear is generated by destroying Invaders and by certain Powers:
- Destroying a Town = 1 Fear. Destroying a City = 2 Fear.

For each Fear, advance one marker from the Fear Pool to Generated Fear. When all markers advance, earn a Fear Card. Markers reset; leftover Fear stays generated.

Crossing a Terror divider raises the Terror Level (better victory conditions). Earned Fear Cards resolve during the next Invader Phase, using the effect of the current Terror Level.`,
  },
  {
    title: 'Boards & Lands',
    body: `Solo mode uses a single 8-land board. Each board has 2 of each terrain (Jungle, Mountain, Sands, Wetland).

ADJACENCY: Two lands are adjacent when they touch (even at a corner).

COASTAL/INLAND: Coastal lands touch the Ocean. The Ocean is not a land.`,
  },
  {
    title: 'Presence',
    body: `Spirit Presence marks the lands a Spirit occupies. If any Spirit has no Presence on the island, the players lose.

SACRED SITES: Lands where a Spirit has more than 1 Presence.

TRACKS: Energy gain and Card Plays come from Presence Tracks. Take Presence from left to right when placing onto the board.`,
  },
  {
    title: 'Powers',
    body: `ELEMENTS: Gained when a Power Card is paid for. Eight Elements: Sun, Moon, Fire, Air, Water, Earth, Plant, Animal. Cleared at Time Passes.

ELEMENTAL THRESHOLDS: Optional effects gated by gained Elements. Resolve top-to-bottom if you meet multiple.

ENERGY COST: Red circle = Fast. Blue circle = Slow.

RANGE: How many lands away from your Presence. Range 0 = your own land.

INNATE POWERS: Always available; cost no Energy/Card Plays; gated by Elements.`,
  },
  {
    title: 'Invaders',
    body: `EXPLORER: 1 HP, 1 Damage.
TOWN: 2 HP, 2 Damage. Source for Explore. 1 Fear when destroyed.
CITY: 3 HP, 3 Damage. Source for Explore. 2 Fear when destroyed.

Damage clears at Time Passes if the Invader survived.`,
  },
  {
    title: 'Blight',
    body: `Blight is added during Ravages of 2+ damage. Take from the Blight Card.

CASCADE: If the land already has Blight, also add Blight to 1 adjacent land. Continues until landing on a clean land.

DESTROY PRESENCE: When Blight is added, destroy 1 Presence from each Spirit in that land.

BLIGHT CARD: Starts Healthy side. Empties → flips to Blighted Island. Empties again → loss (for standard cards). Still-Healthy variants do not cause loss.`,
  },
  {
    title: 'Dahan',
    body: `Each board starts with 6 Dahan. They have 2 HP and deal 2 Damage when Fighting Back.

After Invaders Ravage, surviving Dahan in that land each deal 2 Damage to the Invaders.`,
  },
  {
    title: 'Solo Mode',
    body: `Solo games work like normal games but with a single board.

The luck of the draw is high, with no fellow Spirits to compensate. Spirits may target themselves with Powers that specifically target "Another Spirit", but gain no extra benefit from such effects.`,
  },
  {
    title: 'Adversaries',
    body: `Adversaries change Setup and add ongoing effects. All effects up to your chosen Level are cumulative.

BRANDENBURG-PRUSSIA: Faster invader tempo. Few new rules. Good first adversary.

ENGLAND: Buildings everywhere. Spreads Towns/Cities aggressively. Easier for Spirits that wreck Towns.

SWEDEN: Ravages deal extra damage; assimilates Dahan when Invaders dominate. Easier for Spirits that prevent Ravages.`,
  },
];
